// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

// Defines values for MonetaryEventEventType.
const (
	Expense MonetaryEventEventType = "expense"
	Income  MonetaryEventEventType = "income"
)

// Account defines model for Account.
type Account struct {
	Id   *int64  `gorm:"primaryKey" json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Categories defines model for Categories.
type Categories = []Category

// Category defines model for Category.
type Category struct {
	Id   *int64  `gorm:"primaryKey" json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// MonetaryEvent defines model for MonetaryEvent.
type MonetaryEvent struct {
	Account  *Account  `json:"account,omitempty"`
	Category *Category `json:"category,omitempty"`

	// EventType 収入/支出
	EventType MonetaryEventEventType `json:"eventType"`
	Id        *int64                 `gorm:"primaryKey" json:"id,omitempty"`
	Name      string                 `json:"name"`
}

// MonetaryEventEventType 収入/支出
type MonetaryEventEventType string

// MonetaryEvents defines model for MonetaryEvents.
type MonetaryEvents = []MonetaryEvent

// UpdateAccountParams defines parameters for UpdateAccount.
type UpdateAccountParams struct {
	// Name Name of account that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of account that needs to be updated
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateCategoryParams defines parameters for UpdateCategory.
type UpdateCategoryParams struct {
	// Name Name of category that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of category that needs to be updated
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateMonetaryEventParams defines parameters for UpdateMonetaryEvent.
type UpdateMonetaryEventParams struct {
	// Name Name of monetary event that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of monetary event that needs to be updated
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// AddAccountJSONRequestBody defines body for AddAccount for application/json ContentType.
type AddAccountJSONRequestBody = Account

// AddAccountFormdataRequestBody defines body for AddAccount for application/x-www-form-urlencoded ContentType.
type AddAccountFormdataRequestBody = Account

// AddCategoryJSONRequestBody defines body for AddCategory for application/json ContentType.
type AddCategoryJSONRequestBody = Category

// AddCategoryFormdataRequestBody defines body for AddCategory for application/x-www-form-urlencoded ContentType.
type AddCategoryFormdataRequestBody = Category

// AddMonetaryEventJSONRequestBody defines body for AddMonetaryEvent for application/json ContentType.
type AddMonetaryEventJSONRequestBody = MonetaryEvent

// AddMonetaryEventFormdataRequestBody defines body for AddMonetaryEvent for application/x-www-form-urlencoded ContentType.
type AddMonetaryEventFormdataRequestBody = MonetaryEvent
