// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for MonetaryEventEventType.
const (
	MonetaryEventEventTypeExpense MonetaryEventEventType = "expense"
	MonetaryEventEventTypeIncome  MonetaryEventEventType = "income"
)

// Defines values for MonetaryEvent1EventType.
const (
	MonetaryEvent1EventTypeExpense MonetaryEvent1EventType = "expense"
	MonetaryEvent1EventTypeIncome  MonetaryEvent1EventType = "income"
)

// Defines values for MonetaryEvent2EventType.
const (
	Expense MonetaryEvent2EventType = "expense"
	Income  MonetaryEvent2EventType = "income"
)

// Account defines model for Account.
type Account struct {
	Id   *int64  `gorm:"primaryKey" json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Categories defines model for Categories.
type Categories = []Categories_Item

// Categories_Item defines model for Categories.Item.
type Categories_Item struct {
	union json.RawMessage
}

// Category defines model for Category.
type Category struct {
	Id   *int64  `gorm:"primaryKey" json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Category1 defines model for Category1.
type Category1 struct {
	Id   *int64  `gorm:"primaryKey" json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Category2 defines model for Category2.
type Category2 struct {
	Id   *int64  `gorm:"primaryKey" json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// MonetaryEvent defines model for MonetaryEvent.
type MonetaryEvent struct {
	Account  *Account  `json:"account,omitempty"`
	Category *Category `json:"category,omitempty"`

	// EventType 収入/支出
	EventType MonetaryEventEventType `json:"eventType"`
	Id        *int64                 `gorm:"primaryKey" json:"id,omitempty"`
	Name      string                 `json:"name"`
}

// MonetaryEventEventType 収入/支出
type MonetaryEventEventType string

// MonetaryEvent1 defines model for MonetaryEvent1.
type MonetaryEvent1 struct {
	Account  *Account  `json:"account,omitempty"`
	Category *Category `json:"category,omitempty"`

	// EventType 収入/支出
	EventType MonetaryEvent1EventType `json:"eventType"`
	Id        *int64                  `gorm:"primaryKey" json:"id,omitempty"`
	Name      string                  `json:"name"`
}

// MonetaryEvent1EventType 収入/支出
type MonetaryEvent1EventType string

// MonetaryEvent2 defines model for MonetaryEvent2.
type MonetaryEvent2 struct {
	Account  *Account  `json:"account,omitempty"`
	Category *Category `json:"category,omitempty"`

	// EventType 収入/支出
	EventType MonetaryEvent2EventType `json:"eventType"`
	Id        *int64                  `gorm:"primaryKey" json:"id,omitempty"`
	Name      string                  `json:"name"`
}

// MonetaryEvent2EventType 収入/支出
type MonetaryEvent2EventType string

// MonetaryEvents defines model for MonetaryEvents.
type MonetaryEvents = []MonetaryEvents_Item

// MonetaryEvents_Item defines model for MonetaryEvents.Item.
type MonetaryEvents_Item struct {
	union json.RawMessage
}

// UpdateAccountParams defines parameters for UpdateAccount.
type UpdateAccountParams struct {
	// Name Name of account that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of account that needs to be updated
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateCategoryParams defines parameters for UpdateCategory.
type UpdateCategoryParams struct {
	// Name Name of category that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of category that needs to be updated
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateMonetaryEventParams defines parameters for UpdateMonetaryEvent.
type UpdateMonetaryEventParams struct {
	// Name Name of monetary event that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of monetary event that needs to be updated
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// AddAccountJSONRequestBody defines body for AddAccount for application/json ContentType.
type AddAccountJSONRequestBody = Account

// AddAccountFormdataRequestBody defines body for AddAccount for application/x-www-form-urlencoded ContentType.
type AddAccountFormdataRequestBody = Account

// AddCategoryJSONRequestBody defines body for AddCategory for application/json ContentType.
type AddCategoryJSONRequestBody = Category

// AddCategoryFormdataRequestBody defines body for AddCategory for application/x-www-form-urlencoded ContentType.
type AddCategoryFormdataRequestBody = Category

// AddMonetaryEventJSONRequestBody defines body for AddMonetaryEvent for application/json ContentType.
type AddMonetaryEventJSONRequestBody = MonetaryEvent

// AddMonetaryEventFormdataRequestBody defines body for AddMonetaryEvent for application/x-www-form-urlencoded ContentType.
type AddMonetaryEventFormdataRequestBody = MonetaryEvent

// AsCategory1 returns the union data inside the Categories_Item as a Category1
func (t Categories_Item) AsCategory1() (Category1, error) {
	var body Category1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCategory1 overwrites any union data inside the Categories_Item as the provided Category1
func (t *Categories_Item) FromCategory1(v Category1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCategory1 performs a merge with any union data inside the Categories_Item, using the provided Category1
func (t *Categories_Item) MergeCategory1(v Category1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCategory2 returns the union data inside the Categories_Item as a Category2
func (t Categories_Item) AsCategory2() (Category2, error) {
	var body Category2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCategory2 overwrites any union data inside the Categories_Item as the provided Category2
func (t *Categories_Item) FromCategory2(v Category2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCategory2 performs a merge with any union data inside the Categories_Item, using the provided Category2
func (t *Categories_Item) MergeCategory2(v Category2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Categories_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Categories_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMonetaryEvent1 returns the union data inside the MonetaryEvents_Item as a MonetaryEvent1
func (t MonetaryEvents_Item) AsMonetaryEvent1() (MonetaryEvent1, error) {
	var body MonetaryEvent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMonetaryEvent1 overwrites any union data inside the MonetaryEvents_Item as the provided MonetaryEvent1
func (t *MonetaryEvents_Item) FromMonetaryEvent1(v MonetaryEvent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMonetaryEvent1 performs a merge with any union data inside the MonetaryEvents_Item, using the provided MonetaryEvent1
func (t *MonetaryEvents_Item) MergeMonetaryEvent1(v MonetaryEvent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMonetaryEvent2 returns the union data inside the MonetaryEvents_Item as a MonetaryEvent2
func (t MonetaryEvents_Item) AsMonetaryEvent2() (MonetaryEvent2, error) {
	var body MonetaryEvent2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMonetaryEvent2 overwrites any union data inside the MonetaryEvents_Item as the provided MonetaryEvent2
func (t *MonetaryEvents_Item) FromMonetaryEvent2(v MonetaryEvent2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMonetaryEvent2 performs a merge with any union data inside the MonetaryEvents_Item, using the provided MonetaryEvent2
func (t *MonetaryEvents_Item) MergeMonetaryEvent2(v MonetaryEvent2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MonetaryEvents_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MonetaryEvents_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
